# Netlify configuration file
[build]
  # Directory to build
  base = "./"
  # Directory with final static files
  publish = "public/"
  # No build needed - files are already prepared
  command = ""

# Handle SPA rewrites for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200